parameters:
  - name: IsMultiRegionEnabled
    type: boolean
    default: false

pool:
  vmImage: vs2017-win2016

jobs:
  - job: Region_1
    displayName: Performance Agent Instance 1
    variables:
      - group: PerformanceVariableGroup
    steps:
      - checkout: self
      - task: PowerShell@2
        displayName: Update JMX File Parameters
        inputs:
          targetType: inline
          script: "# Change jmeter parameters\n\nsed -i 's/RESOURCE_ID/$(PerfTestResourceId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_ID/$(PerfTestClientId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_SECRET/$(PerfTestClientSecret)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/RAMP_TIME/$(RAMP_TIME)/g' $(JmeterFolderPath)/$(JmeterFileName)\n \nsed -i 's/DURATION/$(DURATION)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/LOOPS/$(LOOPS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/THREADS/$(THREADS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n"
      - task: PowerShell@2
        displayName: Run Performance in Region1
        inputs:
          targetType: filePath
          filePath: ./JMeterAKSPipeline/ExecuteInAKS.ps1
          arguments: '-AKSClusterName $(AKSClusterNameRegion1) -ResourceGroup $(AKSResourceGroupRegion1) -SPNClientId $(AKSSPNClientIdRegion1) -SPNClientSecret $(AKSSPNClientSecretRegion1) -TenantId $(TenantId) -Namespace $(Namespace) -JMeterFolderPath $(JmeterFolderPath) -JMeterFileName $(JmeterFileName) -CSVFileNames "$(CSVFileNames)"'
          pwsh: true
      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        continueOnError: True
        inputs:
          path: $(JmeterFolderPath)/$(AKSClusterNameRegion1)
          artifactName: Results-Region1-$(THREADS)-$(DURATION)

  - ${{ if eq(parameters.IsMultiRegionEnabled, true) }}:
      - job: Region_2
        displayName: Performance Agent Instance 2
        variables:
          - group: PerfVariableGroup
        steps:
          - checkout: self
          - task: PowerShell@2
            displayName: Update Performance parameters
            inputs:
              targetType: inline
              script: "# Change jmeter parameters\n\nsed -i 's/RESOURCE_ID/$(PerfTestResourceId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_ID/$(PerfTestClientId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_SECRET/$(PerfTestClientSecret)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/RAMP_TIME/$(RAMP_TIME)/g' $(JmeterFolderPath)/$(JmeterFileName)\n \nsed -i 's/DURATION/$(DURATION)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/LOOPS/$(LOOPS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/THREADS/$(THREADS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n"
          - task: PowerShell@2
            displayName: Run Performance in Region2
            inputs:
              targetType: filePath
              filePath: ./JMeterAKSPipeline/ExecuteInAKS.ps1
              arguments: '-AKSClusterName $(AKSClusterNameRegion2) -ResourceGroup $(AKSResourceGroupRegion2) -SPNClientId $(AKSSPNClientIdRegion2) -SPNClientSecret $(AKSSPNClientSecretRegion2) -TenantId $(TenantId) -Namespace $(Namespace) -JMeterFolderPath $(JmeterFolderPath) -JMeterFileName $(JmeterFileName) -CSVFileNames "$(CSVFileNames)"'
              pwsh: true
          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifact
            continueOnError: True
            inputs:
              path: $(JmeterFolderPath)/$(AKSClusterNameRegion2)
              artifactName: Results-Region2-$(THREADS)-$(DURATION)
