parameters:
  - name: JmeterFolderPath
    type: string

  - name: JmeterFileName
    type: string

  - name: Threads
    type: number

  - name: Duration
    type: number

  - name: Loops
    type: number

  - name: RampUpTime
    type: number

variables:
  TenantId: "***"
  Namespace: "***"
  ServiceConnection: "***"
  KeyVaultName: "***"
  SecretNames: "@(PerfTestClientSecret, AKSSPNClientSecretRegion1, AKSSPNClientSecretRegion2)"
  CSVFileNames: "users.csv"
  AKSClusterName: "A"
  AKSResourceGroup: "B"
  AKSSPNClientId: "C"
  AKSClusterNameRegion1: ${{ format('"{0}Region1"', variables['AKSClusterName']) }}
  AKSClusterNameRegion2: ${{ format('"{0}Region2"', variables['AKSClusterName']) }}
  AKSResourceGroupRegion1: ${{ format('"{0}Region1"', variables['AKSResourceGroup']) }}
  AKSResourceGroupRegion2: ${{ format('"{0}Region2"', variables['AKSResourceGroup']) }}
  AKSSPNClientIdRegion1: ${{ format('"{0}Region1"', variables['AKSSPNClientId']) }}
  AKSSPNClientIdRegion2: ${{ format('"{0}Region2"', variables['AKSSPNClientId']) }}

jobs:
  - job: Region_1
    displayName: Performance Agent Instance 1
    steps:
      - checkout: self

      - task: AzureCLI@2
        displayName: Get Keyvault Secrets
        inputs:
          azureSubscription: $(ServiceConnection)
          scriptType: ps
          scriptLocation: "scriptPath"
          scriptPath: ./JMeterAKSPipeline/GetKeyVaultSecrets.ps1
          arguments: "-KeyVaultName $(KeyVaultName) -SecretNames $(SecretNames)"

      # - task: PowerShell@2
      #   displayName: Create AKS Cluster
      #   inputs:
      #     targetType: filePath
      #     filePath: ./JMeterAKSPipeline/CreateAksCluster.ps1
      #     arguments: "-AKSClusterName "
      #   condition: "and(succeeded(), eq('${{ parameters.IsClusterRequired }}', true))"

      - task: PowerShell@2
        displayName: Update JMX File Parameters
        inputs:
          targetType: inline
          script: "# Change jmeter parameters\n\nsed -i 's/RESOURCE_ID/${{ parameters.PerfTestResourceId }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/CLIENT_ID/${{ parameters.PerfTestClientId }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/CLIENT_SECRET/$(PerfTestClientSecret)/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/RAMP_TIME/${{ parameters.RampUpTime }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n \nsed -i 's/DURATION/${{ parameters.Duration }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/LOOPS/${{ parameters.Loops }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/THREADS/${{ parameters.Threads }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n"

      - task: PowerShell@2
        displayName: Run Performance in Region1
        inputs:
          targetType: filePath
          filePath: ./JMeterAKSPipeline/ExecuteInAKS.ps1
          arguments: '-AKSClusterName $(AKSClusterNameRegion1) -ResourceGroup $(AKSResourceGroupRegion1) -SPNClientId $(AKSSPNClientIdRegion1) -SPNClientSecret $(AKSSPNClientSecretRegion1) -TenantId $(TenantId) -Namespace $(Namespace) -JMeterFolderPath ${{ parameters.JmeterFolderPath }} -JMeterFileName ${{ parameters.JmeterFileName }} -CSVFileNames "$(CSVFileNames)"'
          pwsh: true

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        continueOnError: True
        inputs:
          path: ${{ parameters.JmeterFolderPath }}/$(AKSClusterNameRegion2)
          artifactName: Results-Region1-${{ parameters.Threads }}-${{ parameters.Duration }}

  - ${{ if eq(parameters.IsMultiRegionEnabled, true) }}:
      - job: Region_2
        displayName: Performance Agent Instance 2

        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: Get Keyvault Secrets
            inputs:
              azureSubscription: $(ServiceConnection)
              scriptType: ps
              scriptLocation: "scriptPath"
              scriptPath: ./JMeterAKSPipeline/GetKeyVaultSecrets.ps1
              arguments: "-KeyVaultName $(KeyVaultName) -SecretNames $(SecretNames)"

          # - task: PowerShell@2
          #   displayName: Create AKS Cluster
          #   inputs:
          #     targetType: filePath
          #     filePath: ./JMeterAKSPipeline/CreateAksCluster.ps1
          #     arguments: "-AKSClusterName "
          #   condition: "and(succeeded(), eq('${{ parameters.IsClusterRequired }}', true))"

          - task: PowerShell@2
            displayName: Update Performance parameters
            inputs:
              targetType: inline
              script: "# Change jmeter parameters\n\nsed -i 's/RESOURCE_ID/${{ parameters.PerfTestResourceId }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/CLIENT_ID/${{ parameters.PerfTestClientId }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/CLIENT_SECRET/$(PerfTestClientSecret)/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/RAMP_TIME/${{ parameters.RampUpTime }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n \nsed -i 's/DURATION/${{ parameters.Duration }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/LOOPS/${{ parameters.Loops }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n\nsed -i 's/THREADS/${{ parameters.Threads }}/g' ${{ parameters.JmeterFolderPath }}/${{ parameters.JmeterFileName }}\n"

          - task: PowerShell@2
            displayName: Run Performance in Region2
            inputs:
              targetType: filePath
              filePath: ./JMeterAKSPipeline/ExecuteInAKS.ps1
              arguments: '-AKSClusterName $(AKSClusterNameRegion2) -ResourceGroup $(AKSResourceGroupRegion2) -SPNClientId $(AKSSPNClientIdRegion2) -SPNClientSecret $(AKSSPNClientSecretRegion2) -TenantId $(TenantId) -Namespace $(Namespace) -JMeterFolderPath ${{ parameters.JmeterFolderPath }} -JMeterFileName ${{ parameters.JmeterFileName }} -CSVFileNames "$(CSVFileNames)"'
              pwsh: true

          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifact
            continueOnError: True
            inputs:
              path: ${{ parameters.JmeterFolderPath }}/$(AKSClusterNameRegion2)
              artifactName: Results-Region2-${{ parameters.Threads }}-${{ parameters.Duration }}
