pool:
  vmImage: "windows-latest"

trigger: none

variables:
  DefaultNamespace: "jmeter"
  AksClusterName: "shdeb-aks-new"
  ResourceGroup: "modiot-ci-perf"
  ServicePrincipalId: "09f10d7d-81bf-470d-be10-279f9ef2c35a"
  AksRegion: '"West US 2"'
  NodeVmSize: "Standard_D2s_v3"
  ServiceConnection: "perf-aks-access"
  KeyVaultName: "dip-perf-execution-kv"
  SecretNames: "perfAADClientSecret"
  Tenant: "microsoft.onmicrosoft.com"

steps:
  - task: AzureKeyVault@1
    displayName: Get Keyvault Secrets
    inputs:
      azureSubscription: $(ServiceConnection)
      KeyVaultName: $(KeyVaultName)
      SecretsFilter: $(SecretNames)
      RunAsPreJob: true

  - task: PowerShell@2
    displayName: "Create AKS Cluster"
    inputs:
      targetType: filePath
      filePath: "./JMeterAKSPipeline/CreateLoadTestInfra.ps1"
      arguments: "-tenant $(Tenant) -defaultNamespace $(DefaultNamespace) -resourceGroup $(ResourceGroup) -aksClusterName $(AksClusterName) -spnClientId $(ServicePrincipalId) -spnClientSecret $(perfAADClientSecret) -aksRegion $(AksRegion) -nodeVmSize $(NodeVmSize)"